// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/websrv/msgproto/msg.proto

package msgproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SayHello service

type SayHelloService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type sayHelloService struct {
	c    client.Client
	name string
}

func NewSayHelloService(name string, c client.Client) SayHelloService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "msgproto"
	}
	return &sayHelloService{
		c:    c,
		name: name,
	}
}

func (c *sayHelloService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SayHello.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SayHello service

type SayHelloHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterSayHelloHandler(s server.Server, hdlr SayHelloHandler, opts ...server.HandlerOption) error {
	type sayHello interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type SayHello struct {
		sayHello
	}
	h := &sayHelloHandler{hdlr}
	return s.Handle(s.NewHandler(&SayHello{h}, opts...))
}

type sayHelloHandler struct {
	SayHelloHandler
}

func (h *sayHelloHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.SayHelloHandler.Hello(ctx, in, out)
}
